### ISSUE TITLE
module 'invokust' has no attribute 'create_settings'

### ISSUE THREAD

**Issue by DimsumPanda** [FutureSharks/invokust#15]
Hi, I am trying to run the invokust file locally, but I encounter the `module 'invokust' has no attribute 'create_settings'` error on the `settings = invokust.create_settings(` line.
I am using the second example in the readme against my own endpoints. Am I not able to run this locally on a windows machine?
```
import invokust

from locust import HttpLocust, TaskSet, task

class Task(TaskSet):
    @task()
    def get_home_page(self):
        '''
        Gets /
        '''
        self.client.get("/")

class WebsiteUser(HttpLocust):
    task_set = Task

settings = invokust.create_settings(
    classes=[WebsiteUser],
    host='http://example.com',
    num_requests=10,
    num_clients=1,
    hatch_rate=1
    )

loadtest = invokust.LocustLoadTest(settings)
loadtest.run()
loadtest.stats()
```

**Comment by FutureSharks** [comment]
Hi @DimsumPanda,
I don't think you can run this on Windows due to `signal` here:
https://github.com/FutureSharks/invokust/blob/master/invokust/loadtest.py#L26

But I would expect a different error from this?

**Comment by akursar** [comment]
We're working around this for now with

    settings = invokust.create_settings(...)
    settings.no_reset_stats = True
    loadtest = invokust .LocustLoadTest(settings)

**Comment by akursar** [comment]
Doh, sorry, misread the error. I thought this was a problem with the no_reset_stats attribute being missing, which is something we've hit.

**Comment by DimsumPanda** [comment]
Wow, thank you for the quick response. 
Would I be able to test on Linux or do I just go straight to Lambda and test?

**Comment by FutureSharks** [comment]
Cool.

There's 2 parts to this project:
1. Running locust load test in python
2. Running locust load test in python, on AWS Lambda

They are separate. You can totally do 1 on Linux (or docker on Windows) without AWS Lambda :)

**Comment by DimsumPanda** [comment]
Thank you, I will try that then!

**Comment by DimsumPanda** [comment]
I tried this in a Centos Linux instance and ran the file. I still get `'module' object has no attribute 'create_settings'`, any idea what I might be doing wrong?

**Comment by FutureSharks** [comment]
Can you paste your complete code with output from your terminal?

**Comment by DimsumPanda** [comment]
Sorry it seems there's some trouble with running Python 3 on that Linux instance, so that might be the problem.
