### ISSUE TITLE
Change license to be compatible with Locust

### ISSUE THREAD

**Issue by vamega** [FutureSharks/invokust#18]
Hi.

I really like the approach you've taken here.
Would you be willing to change the license to a license that is compatible with locustio?

As it stands it's not possible to use this code as the basis of something that I can submit as a PR to locust with.

Thanks

**Comment by FutureSharks** [comment]
I can change it.

What to? MIT?

What part of this code are you submitting to the locust code base?

**Comment by vamega** [comment]
MIT would be ideal.
I'd want to reuse some of the structure of `loadtest.py`.
I'd need to extend it to support master/slave mode, and remove references to the now deprecated `num_requests` option.

I'm still experimenting with a lot of this privately, so I'm not sure exactly what I'd lift. However keeping it as MIT would allow me to use parts of it vs. having to reimplement similar ideas without reference to this.

Thanks

**Comment by FutureSharks** [comment]
https://github.com/FutureSharks/invokust/pull/19
