### ISSUE TITLE
num_requests option is deprecated

### ISSUE THREAD

**Issue by FutureSharks** [FutureSharks/invokust#20]
According to @vamega.

We probably need to update the code here.

**Comment by vamega** [comment]
Here's the [commit](https://github.com/locustio/locust/commit/d4361cc6bb3dbc8348636bbb85ec3fc1572703f7) where it got removed.
I think it's useful, and would support adding it back, but I don't know the maintainer's opinions on brining back this functionality.

**Comment by FutureSharks** [comment]
Actually I think for this project `run_time` is much better. The problem fo invokust is that we want to run the most requests possible in the time before the AWS Lambda execution time limit. Previously it was a guess. So this is easier to work with.
