### ISSUE TITLE
support locustio 0.8.1

### ISSUE THREAD

**Issue by af6140** [FutureSharks/invokust#21]
This is latest release, the pypi 0.44 is pinned to locustio 0.8a2?

**Comment by af6140** [comment]
the version of locustio 0.8a2  not compatible with latest gevent.

**Comment by FutureSharks** [comment]
I see. Could you make a PR?

**Comment by FutureSharks** [comment]
And obviously test it works 🙂

**Comment by FutureSharks** [comment]
Now version `0.9.0` is supported.
