### ISSUE TITLE
Version parity with Locust 0.11?

### ISSUE THREAD

**Issue by rokcarl** [FutureSharks/invokust#25]
It now runs with locust 0.9, but locust 0.11 is already out and it does not work with it.
Is it possible to bring it to support locust 0.11?

**Comment by FutureSharks** [comment]
Sure thing @rokcarl! Just make a PR 😃

**Comment by rokcarl** [comment]
I'm a bit tight in my schedule. I'll see what I can do. I was hoping someone else might take care of it.
It would be better if Locust itself would support this...

**Comment by FutureSharks** [comment]
> I was hoping someone else might take care of it.

Haha story of my life

> It would be better if Locust itself would support this...

You mean running on AWS Lambda? Or better support for running from within Python itself?

**Comment by rokcarl** [comment]
Better support for running within Python.

**Comment by M1strall** [comment]
Opened PR for locust 0.13.5 support
https://github.com/FutureSharks/invokust/pull/28

**Comment by FutureSharks** [comment]
Merged and released version 0.61 to pypi.
