### ISSUE TITLE
Gevent dependency error when running through AWS

### ISSUE THREAD

**Issue by cstipes-shipt** [FutureSharks/invokust#26]
I get this error believe whenever I try to run on zipped dependencies on AWS.

{
  "errorMessage": "Unable to import module 'lambda_locust': No module named 'gevent.__hub_local'",
  "errorType": "Runtime.ImportModuleError"
}

Packaging code with with in Makefile:
PYTHON_VERSION=3.7
ZIP_PATH=$(abspath ./build.zip)

zip:
	$(eval VENV=$(shell pipenv --venv))
	cd ${VENV}/lib/python${PYTHON_VERSION}/site-packages/ && zip -r ${ZIP_FILE} .
	zip -r ${ZIP_PATH} . -x *.git*

I've gotten my handler paired down to only printing the event, but it fails at importing dependencies: 

import sys
import os
sys.path.insert(0, "python-packages")
import logging
import json

from invokust.aws_lambda import get_lambda_runtime_info
from invokust import LocustLoadTest, create_settings

logging.basicConfig(level=logging.INFO)

def handler(event=None, context=None):
    print(str(event))
    # try:
    #     if event:
    #         settings = create_settings(**event)
    #     else:
    #         settings = create_settings(from_environment=True)
    #
    #     loadtest = LocustLoadTest(settings)
    #     loadtest.run()
    #
    # except Exception as e:
    #     logging.error("Locust exception {0}".format(repr(e)))
    #
    # else:
    #     locust_stats = loadtest.stats()
    #     lambda_runtime_info = get_lambda_runtime_info(context)
    #     loadtest_results = locust_stats.copy()
    #     loadtest_results.update(lambda_runtime_info)
    #     json_results = json.dumps(loadtest_results)
    #
    #     logging.info(json_results)
    #     return json_results

**Comment by tobHai** [comment]
I think the problem is running python 3.7.
I created the lambda zip locally on python 3.6 and had no issues running it on AWS. 
Now I tried to use CodeBuild (python 3.7) to update the lambda code and I get the same error.

**Comment by cstipes-shipt** [comment]
I figured this out, sorry for the spam. My zip command did not work. Using the aws SAM cli to package my dependencies did the trick.

**Comment by FutureSharks** [comment]
Glad you got it resolve!
