### ISSUE TITLE
Implementation of the called lambda when running parallel load test

### ISSUE THREAD

**Issue by tobHai** [FutureSharks/invokust#27]
I'm trying to understand the example provided at the bottom of the Readme about running the load test in parallel.

Unfortunately I do not fully grasp how the called lambda_locust function should look like.
```
def handler(event=None):
 # create settings from payload 
 settings = invokust.create_settings(event )
 loadtest = invokust.LocustLoadTest(settings)
 loadtest.run()
```
Should it just accept the JSON payload and run a standard load test ? Or do I have to change the settings according to the number of threads passed to the LambdaLoadTest class?

**Comment by FutureSharks** [comment]
It's a little bit of trial and error and really depends on what is happening in your load test.

The settings that are passed to `LambdaLoadTest` as `lambda_payload` are the settings for a single AWS Lambda execution of your load test. You could have the execution run with 1 client or 1000 clients. But if your locustfile is doing a lot of complex things then your lambda execution might run out of memory.

The `threads` setting is how many parallel Lambda executions will happen.

**Comment by IsaacVaswani-Casas** [comment]
I have a test much like the example function given except running within a handler, however it seems to be invoking as many Lambdas as it possibly can (10,000 in 3 minutes before it got throttled) and outright ignoring the 2 thread limit. Is this due to the scope of the handler function when being called?

**Comment by FutureSharks** [comment]
Maybe set `wait_time` in your locust file to limit the throughput?

e.g.

```python
from locust import Locust, TaskSet, task, between

class MyTaskSet(TaskSet):
    @task
    def my_task(self):
        print("executing my_task")

class User(Locust):
    task_set = MyTaskSet
    wait_time = between(5, 15)
```

**Comment by FutureSharks** [comment]
Closing as no reply.
