### ISSUE TITLE
Num of request being made doesnt match with the settings.

### ISSUE THREAD

**Issue by gouseferoz** [FutureSharks/invokust#29]
Hi,

I was running my invokust with the below settings,

```
settings = invokust.create_settings(
    classes=[WebsiteUser],
    host='https://google.com',
    num_clients=1,
    hatch_rate=1,
    run_time='10s'
)
```

WIth the above settings i should see 10 requests being made, as the hatch_rate is 1 and time limit is 10s.

But i see 51 requests being made in this 10s duration.

```
{
  "requests": {
    "GET_/": {
      "request_type": "GET",
      "num_requests": 51,
      "min_response_time": 139.55307006835938,
      "median_response_time": 180,
```

**Comment by FutureSharks** [comment]
Hi @gouseferoz, hatch rate is not related to requests directly. This is how many clients are started per second. How many requests your client makes will be defined in your load test although it's not exact.

Here's some doc to help: https://docs.locust.io/en/stable/api.html#module-locust.wait_time

**Comment by FutureSharks** [comment]
Closing as no reply.
