### ISSUE TITLE
Updating Locsut version

### ISSUE THREAD

**Issue by yiss** [FutureSharks/invokust#30]
Hi, thank you for this framework. I was wondering if you can update the version of locsut please? Thank you!

**Comment by FutureSharks** [comment]
PRs welcome 🙂

**Comment by CsilLAB** [comment]
Locust has now a new major version, I would like to work on it to make it compatible with 1.0.3. I am happy to be assigned to this issue @FutureSharks if you don't mind. :)

**Comment by FutureSharks** [comment]
> I am happy to be assigned to this issue 

Sure thing!

**Comment by TalAbramson** [comment]
Will this fix this issue? 
    load_test = invokust.LocustLoadTest(setting)
  File "C:\Python38\lib\site-packages\invokust\loadtest.py", line 24, in __init__
    gevent.signal(signal.SIGTERM, self.sig_term_handler)
TypeError: 'module' object is not callable

**Comment by CsilLAB** [comment]
There are quite substantial changes needed in invokust to support the new major version.

**Comment by TalAbramson** [comment]
How can i obtain the previous Locsut version that invokust support?
i couldn't locate any version below 1.0

**Comment by FutureSharks** [comment]
There was some naming changes, locust vs locustio. You can find the old versions under the other name: https://pypi.org/project/locustio/#history
