### ISSUE TITLE
Error invoking lambda following quickstart

### ISSUE THREAD

**Issue by michela** [FutureSharks/invokust#32]
Running py3.8, I was able to create a lambda not not invoke it

Getting usage errrors locally

`
aws lambda invoke --function-name lambda_locust --invocation-type RequestResponse --payload '{"locustfile": "my_locustfile.py", "host":"https://miamioh-gradify.com", "num_requests":"20", "num_clients": "1", "hatch_rate": "1", "run_time":"3m"}' output.txt

Unknown options: num_requests:20,, num_clients:, 1,, hatch_rate:, 1,, run_time:3m}', output.txt, host:https://miamioh-gradify.com,`

Same via aws-shell

Tried creating test in Lambda Console.

{
  "locustfile": "my_locustfile.py",
  "host": "https://miamioh-gradify.com",
  "num_requests": "20",
  "num_clients": "1",
  "hatch_rate": "1",
  "run_time": "3m"
}

but got 
{
  "errorMessage": "Unable to import module 'lambda_locust': No module named 'gevent.__hub_local'",
  "errorType": "Runtime.ImportModuleError"
}

**Comment by CsilLAB** [comment]
@michela, have you managed to resolve this?

This issue happened to me when packaged the app on Mac and not using the docker container as advised in the README.md. The reason for my problem was that some of the dependencies (for example `gevent`) are complied locally for darwin architecture, but that cannot be used in Lambda, so the binaries needed are actually not there.

**Comment by michela** [comment]
No, I gave up. Thanks for info. I was testing from Debian and not using docker.

**Comment by bennyhartnett** [comment]
Same exact issue happened to me from Amazon Linux 2
