### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by csillabessenyei** [FutureSharks/invokust#34]
Would you consider adopting [semantic versioning](https://semver.org/)?

I have seen your the release version was bumped up from 0.61 to 0.7 yesterday. 

Chronologically 0.7 is newer than 0.61, but mathematically isn't. While I understand the logic behind it, it will cause problems with dependency management.

I'd like to specify the requirements as `invokust>=0.7`, this would not change as 0.61 is larger as pip interprets it.

**Comment by FutureSharks** [comment]
You're right. My mistake! Resolved here: https://pypi.org/project/invokust/0.71/

Cool?

**Comment by csillabessenyei** [comment]
Amazing, thanks for the fast action! 🥳
