### ISSUE TITLE
version 0.75 missing for Pypi

### ISSUE THREAD

**Issue by anotinelg** [FutureSharks/invokust#40]
HI, are you planning to publish 0.75 to Pypi?
Currently, it seems that only the 0.73 is published, the 0.73 is linked to an old version of locust.
Thank you

**Comment by FutureSharks** [comment]
0.75, 0.74 and 0.73 are all the same. I was just testing the automated pypi release github action 🙂

So I created a new release here: https://github.com/FutureSharks/invokust/releases/tag/1.0a

Just waiting to see if it is pushed to pypi now...

**Comment by anotinelg** [comment]
Oh sorry, what i wanted is a version which links to the new version of locust > 1.0.3.  I thought it was 0.75, but actually it is only on Master. Do you plan to create a 0.76 version? thanks

**Comment by FutureSharks** [comment]
Yep, you can install it `pip install invokust==1.0a0`
