### ISSUE TITLE
Handle environment variables with `LambdaLoadTest` on Locust

### ISSUE THREAD

**Issue by asantoz** [FutureSharks/invokust#42]
Hi :)

I have a use case that I need to add environment variables with some settings to use on Locust.
I'm using at moment `LambdaLoadTest` method to run my lambda function, there is any way to do it?

Thanks 🙏

**Comment by CsilLAB** [comment]
What would you like to control with env vars exactly?

You can find details on what's supported here in the README.md and the code here: https://github.com/FutureSharks/invokust/blob/master/invokust/settings.py

You'll need to set `from_environment` to True if you want to pull values from env vars.

The classes part is broken, I'm planning to remove that from the code at some point.

**Comment by CsilLAB** [comment]
Hang on, what I said is not for `LambdaLoadTest`. Sorry. I don't think what you're after is currently supported.

**Comment by FutureSharks** [comment]
> add environment variables with some settings to use on Locust

You mean simply to use in your locust file? Can you just add [env vars](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html) and then access them with `os.environ['MY_VAR']`?

**Comment by FutureSharks** [comment]
Closing as no reply.
