### ISSUE TITLE
Unable to use invokust. locust version == 1.3.0, locustio==0.13.5, invokust==0.73

### ISSUE THREAD

**Issue by bondnotanymore** [FutureSharks/invokust#45]
I have a following directory structure.

<img width="1536" alt="Screenshot 2020-12-11 at 10 33 25 PM" src="https://user-images.githubusercontent.com/31071589/101933085-b2f58200-3c01-11eb-84ba-a319306af3cd.png">

```
myapp.py is a simple flask application running locally
locustfile.py is my locust file
run_locust.py is where i have put the invokust code.

```
All 3 files attached.
[Files.zip](https://github.com/FutureSharks/invokust/files/5680558/Files.zip)

When i run run_locust.py like this:
```
python run_locust.py, I keep getting this error

/Users/kapilmathur/virtual_envs/audit_trail_auto/bin/python3.8 /Users/kapilmathur/repos/Load-tools/Load-test/run_locust.py
Traceback (most recent call last):
  File "/Users/kapilmathur/repos/Load-tools/Load-test/run_locust.py", line 8, in <module>
    settings = create_settings(
  File "/Users/kapilmathur/virtual_envs/audit_trail_auto/lib/python3.8/site-packages/invokust/settings.py", line 68, in create_settings
    docstring, classes = load_locustfile(settings.locustfile)
ValueError: too many values to unpack (expected 2)

Process finished with exit code 1
```

Can you plz help with the issue and tell me if i am using it correctly. is there some version dependency/conflict I am hitting ?

**Comment by kmels** [comment]
Same issue here with locust==1.4.1

**Comment by bondnotanymore** [comment]
Lets wait for lib-owners to advise and comment

**Comment by FutureSharks** [comment]
You will need to use `locust==1.1.1` until invokust is updated. The problem is that `load_locustfile` from the locust project now returns 3 items `imported.__doc__, user_classes, shape_class`: https://github.com/locustio/locust/blob/487098e21929247f07bb0cab954da43ac0aae076/locust/main.py#L99

**Comment by bondnotanymore** [comment]
Thanks @FutureSharks .. I will try the version advised and update here if it works.
Btw, the way i am running the file having invokust code is the right way to run it ?? Can you plz comment on that as well?

**Comment by bondnotanymore** [comment]
Also, what is the python version you recommend with that combination @FutureSharks ?

**Comment by FutureSharks** [comment]
> Btw, the way i am running the file having invokust code is the right way to run it ?? Can you plz comment on that as well?

Well, if you're running it from the command line like `python run_locust.py` then I think just don't use invokust and simply use locust directly.

> Also, what is the python version you recommend with that combination

It's only tested with 3.7 but I think 3.9 should also work fine.
