### ISSUE TITLE
gevent error when attempting to invoke lambda

### ISSUE THREAD

**Issue by sgalliver** [FutureSharks/invokust#47]
Hi,

I'm working my way through the instructions in the README for running the sample code on AWS Lambda.  I've worked my way through a variety of errors, but have bumped up on one that has me stymied.  I'm hoping you can help.

I'm working on a MacBook Pro, running Catalina (10.15.7), so I'm using docker to compile the python package, as described in the README:
```
docker run -it --volume=$PWD:/temp python:3.6 bash -c "pip install /temp --target=/temp/python-packages"
```

Then I'm zipping and creating the lambda, no problem.
```
zip -q -r lambda_locust.zip lambda_locust.py locustfile_example.py python-packages

aws --profile sandbox lambda create-function --function-name lambda_locust --timeout 300 --memory-size 256 --runtime python3.6 --role arn:aws:iam::039069484348:role/service-role/sdg-test-function-role-54kv5be3 --handler lambda_locust.handler --zip-file fileb://lambda_locust.zip
```
As an aside, you have a note in your TODO.md about `Process exited before completing request` errors. I was getting that too, but I fixed it by doubling the memory size. Also, that role in my `create-function` command is a basic lambda execution role.

Finally, invoking the lambda gets me this:
```
(invokust) SGALLIVER-MBP:invokust sgalliver$ aws --profile sandbox lambda invoke --function-name lambda_locust --invocation-type RequestResponse --payload '{"locustfile": "locustfile_example.py", "host":"http://www.google.com", "num_users": "1", "spawn_rate": "1", "run_time":"1m"}' output.txt --log-type Tail --query 'LogResult' --output text | base64 -d
START RequestId: c8d8bbbf-4e5c-4f20-bd56-f00c3bf000eb Version: $LATEST
[2021-01-13 17:47:35,008] 169.254.244.125/ERROR/root: Locust exception ImportError("/lib64/libc.so.6: version `GLIBC_2.28' not found (required by python-packages/gevent/libuv/_corecffi.abi3.so)",)
END RequestId: c8d8bbbf-4e5c-4f20-bd56-f00c3bf000eb
REPORT RequestId: c8d8bbbf-4e5c-4f20-bd56-f00c3bf000eb	Duration: 3.73 ms	Billed Duration: 4 ms	Memory Size: 256 MB	Max Memory Used: 121 MB	Init Duration: 1272.77 ms
```

Any clues about that import error? I did [some poking around](https://stackoverflow.com/questions/36244563/unable-to-import-grequests-for-aws-lambda?noredirect=1&lq=1) and it appears that gevent needs to be compiled on an Amazon Linux instance. I suppose I could go spin up an EC2 instance, but I figured the README would have mentioned it if that were necessary. So I thought I'd ask if you have hit this error and how you solved it, before I go running down the EC2 rabbithole.

Many thanks!

**Comment by FutureSharks** [comment]
Hi @sgalliver 

> I've worked my way through a variety of errors

Feel free to make a PR to improve the README if there's missing things.

> As an aside, you have a note in your TODO.md about Process exited before completing request errors. I was getting that too, but I fixed it by doubling the memory size. 

Good to know, thanks!

> Locust exception ImportError("/lib64/libc.so.6: version `GLIBC_2.28' not found (required by python-packages/gevent/libuv/_corecffi.abi3.so)",)

I think this is because the `python:3.6` docker image uses GLIBC `2.28`:

```
$ docker run -it python:3.6 ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
```

And AWS does not any more. There's https://github.com/aws/aws-lambda-base-images/issues/5 that seems to indicate that AWS uses version `2.26` so perhaps you can find an older python docker image that uses this version and use that to create the `python-packages` directory? Perhaps an older version of `python:3.6`.

**Comment by sgalliver** [comment]
I'll give it a go. Thanks for getting back to me.

**Comment by FutureSharks** [comment]
@sgalliver come back and update this issue if you resolve it 🙂
