### ISSUE TITLE
Use invokust with odoo

### ISSUE THREAD

**Issue by jhoffmannAmetras** [FutureSharks/invokust#61]
Hey Guys,
I have a question regarding your Locust-wrapper. Is it possible to load test Odoo applications over jsonrpc ? 
I currently have the problem that my Locust tests are running but not returning any test results on my CLI. If someone knows something about this just hit me up!

**Comment by FutureSharks** [comment]
Hi @jhoffmannAmetras,

> Is it possible to load test Odoo applications over jsonrpc ?

Before using `invokust`, does your test work in plain locust?

**Comment by jhoffmannAmetras** [comment]
> Hi @jhoffmannAmetras,
> 
> > Is it possible to load test Odoo applications over jsonrpc ?
> 
> Before using `invokust`, does your test work in plain locust?

Yes, it worked without any problem.

**Comment by FutureSharks** [comment]
Then I would check Cloudwatch:
- Check the log output from the Lambda executions
- Check the metrics for memory usage, perhaps it's using too much and being killed
